services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    command: '--lower_case_table_names=1'
    environment:
      - 'MYSQL_DATABASE=iotcomm'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS=1'
    ports:
      - '3306:3306'
    volumes:
      - 'C:/Users/whddl/IdeaProjects/LibraEnd/src/main/resources/sql:/docker-entrypoint-initdb.d'
    networks:
      - default
      - our_net
  application:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'mysql'
    links:
      - mysql
    ports:
      - '8080:8080'
    container_name: LibraEnd

    #    environment:
    #      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/userdb
    #      SPRING_DATASOURCE_USERNAME: user
    #      SPRING_DATASOURCE_PASSWORD: userpwd
    restart: always
    networks:
      - default
      - our_net

networks:
  our_net:
    driver: bridge