services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  mqtt:
    image: eclipse-mosquitto:1.6.4
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /workspaces/docker-workspaces/mqtt/config:/mosquitto/config
      - /workspaces/docker-workspaces/mqtt/data:/mosquitto/data
      - /workspaces/docker-workspaces/mqtt/log:/mosquitto/log