services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
#  mqtt:
#    image: eclipse-mosquitto:2.0.15
#    ports:
#      - "1883:1883"
#      - "9001:9001"
#    volumes:
#      - ./src/main/resources/mqtt/config/mqtt.conf:/mosquitto/config/mosquitto.conf
#      - ./src/main/resources/mqtt/config/passwd:/mosquitto/config/passwd
##      - /workspaces/docker-workspaces/mqtt/data:/mosquitto/data
##      - /workspaces/docker-workspaces/mqtt/log:/mosquitto/log